export const UPDATE_TRAINS_INFO = 'UPDATE_TRAINS_INFO';
export const UPDATE_TRAINS_DETAILS = 'UPDATE_TRAINS_DETAILS';
export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS';
export const SET_GET_TRAINS_INFO_ERROR = 'SET_GET_TRAINS_INFO_ERROR';
export const SET_GET_TRAIN_DETAILS_ERROR = 'SET_GET_TRAIN_DETAILS_ERROR';
